// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSyq1K4fHf7glk0S4W9wU2yLALL54M7FE',
    appId: '1:298772039624:web:f70dcc20e97fb4368622fd',
    messagingSenderId: '298772039624',
    projectId: 'bikeservicingapp-7b10c',
    authDomain: 'bikeservicingapp-7b10c.firebaseapp.com',
    storageBucket: 'bikeservicingapp-7b10c.firebasestorage.app',
    measurementId: 'G-5BVH8DYQ4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvtHGF2b8sAzKGMoAuYbDnORA1yrTL9Xg',
    appId: '1:298772039624:android:49627ac608fb59788622fd',
    messagingSenderId: '298772039624',
    projectId: 'bikeservicingapp-7b10c',
    storageBucket: 'bikeservicingapp-7b10c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOLRezVwAdiqAAxnXy9JOASIJpXvRaskk',
    appId: '1:298772039624:ios:9e8af031e0e899018622fd',
    messagingSenderId: '298772039624',
    projectId: 'bikeservicingapp-7b10c',
    storageBucket: 'bikeservicingapp-7b10c.firebasestorage.app',
    iosBundleId: 'com.example.bikeServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOLRezVwAdiqAAxnXy9JOASIJpXvRaskk',
    appId: '1:298772039624:ios:9e8af031e0e899018622fd',
    messagingSenderId: '298772039624',
    projectId: 'bikeservicingapp-7b10c',
    storageBucket: 'bikeservicingapp-7b10c.firebasestorage.app',
    iosBundleId: 'com.example.bikeServiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSyq1K4fHf7glk0S4W9wU2yLALL54M7FE',
    appId: '1:298772039624:web:29733961b70317c18622fd',
    messagingSenderId: '298772039624',
    projectId: 'bikeservicingapp-7b10c',
    authDomain: 'bikeservicingapp-7b10c.firebaseapp.com',
    storageBucket: 'bikeservicingapp-7b10c.firebasestorage.app',
    measurementId: 'G-DD60G08FEL',
  );
}
